name: OpenGrep PR Scan

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  opengrep-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch latest OpenGrep version
      id: get-version
      run: |
        VERSION=$(curl -s https://api.github.com/repos/opengrep/opengrep/releases/latest | jq -r .tag_name)
        echo "OPENGREP_VERSION=${VERSION#v}" >> $GITHUB_ENV
        echo "VERSION_TAG=$VERSION" >> $GITHUB_OUTPUT

    - name: Download and install OpenGrep
      run: |
        curl -L -o opengrep "https://github.com/opengrep/opengrep/releases/download/${{ steps.get-version.outputs.VERSION_TAG }}/opengrep-linux-x86_64"
        chmod +x opengrep
        sudo mv opengrep /usr/local/bin/opengrep

    - name: Set up Git for diff
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1

    - name: Get changed files
      id: changed-files
      run: |
        FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | tr '\n' ' ')
        echo "FILES=$FILES" >> $GITHUB_OUTPUT

    - name: Run OpenGrep scan
      if: steps.changed-files.outputs.FILES != ''
      run: |
        echo "Scanning changed files with OpenGrep..."
        opengrep scan ${{ steps.changed-files.outputs.FILES }}
        
