on: 
 push:
 workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    env:
       ZAP_AUTH_HEADER: Cookie
       ZAP_AUTH_HEADER_VALUE: session=${{ secrets.TOKEN }}
       ZAP_AUTH_HEADER_SITE: py-sqli.onrender.com
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://py-sqli.onrender.com/xss-demo'
          cmd_options: '-a'
