on: 
 push:
 workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    env:
       ZAP_AUTH_HEADER: Cookie
       ZAP_AUTH_HEADER_VALUE: session=${{ secrets.TOKEN }}
       ZAP_AUTH_HEADER_SITE: py-sqli.onrender.com
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: 'https://py-sqli.onrender.com'
